version: '2.4'

services:
  sistc-minio:
    image: minio/minio
    container_name: sistc-minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - 9000:9000
    command: server /data